--Câu 2:
--a)
SELECT *, VITRI.STArea() AS DIENTICH, VITRI.STArea()*LUONGNUOC AS LUONGNUOCTUOI
FROM QLDAT
GO
--b)
SELECT *, QL.VITRI.STArea() AS DIENTICH
FROM QLDAT QL
WHERE QL.VITRI.STArea() <= ALL(SELECT VITRI.STArea()
							FROM QLDAT)
GO
--c)
DECLARE @KENH GEOMETRY = GEOMETRY::STGeomFromText('POLYGON((2 -2,2 4,4 4,4 -2,2 -2))',0)
SELECT MA,VITRI.STIntersection(@KENH) AS VITRIGOIHAN, VITRI.STIntersection(@KENH).STArea() AS DIENTICHMAT
FROM QLDAT
GO
